ingenieria_profesor_homepage:
    path:     /profesor
    defaults: { _controller: IngenieriaProfesorBundle:Default:index }

ingenieria_profesor_estudiantes:
    path:     /profesor/sus-estudiantes
    defaults: { _controller: IngenieriaProfesorBundle:Default:estudiantes }

ingenieria_profesor_registrarestudiante:
    path:     /profesor/sus-estudiantes
    defaults: { _controller: IngenieriaProfesorBundle:Default:registrarEstudiante }

ingenieria_profesor_actividades:
    path:     /profesor/actividades
    defaults: { _controller: IngenieriaProfesorBundle:Default:actividades }

ingenieria_profesor_registraractividad:
    path:     /profesor/registrar-actividad
    defaults: { _controller: IngenieriaProfesorBundle:Default:registrarActividad }

ingenieria_profesor_actividad:
    pattern:  /profesor/actividad/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:actividad }

ingenieria_profesor_cronograma:
    pattern:  /profesor/cronograma/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:cronograma }

ingenieria_profesor_aprobarcronograma:
    pattern:  /profesor/aprobar-cronograma/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:aprobar }

ingenieria_profesor_rechazarcronograma:
    pattern:  /profesor/rechazar-cronograma/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:rechazar }

ingenieria_profesor_bitacora:
    pattern:  /profesor/bitacora/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:bitacora }

ingenieria_profesor_verificarActividad:
    path:     /profesor/verificaractividad
    defaults: { _controller: IngenieriaProfesorBundle:Default:verificarActividad }
