ingenieria_profesor_homepage:
    path:     /profesor
    defaults: { _controller: IngenieriaProfesorBundle:Default:index }

ingenieria_profesor_estudiantes:
    path:     /profesor/sus-estudiantes
    defaults: { _controller: IngenieriaProfesorBundle:Default:estudiantes }

ingenieria_profesor_registrarestudiante:
    path:     /profesor/sus-estudiantes
    defaults: { _controller: IngenieriaProfesorBundle:Default:registrarEstudiante }

ingenieria_profesor_actividades:
    path:     /profesor/actividades
    defaults: { _controller: IngenieriaProfesorBundle:Default:actividades }

ingenieria_profesor_registraractividad:
    path:     /profesor/registrar-actividad
    defaults: { _controller: IngenieriaProfesorBundle:Default:registrarActividad }

ingenieria_profesor_actividad:
    pattern:  /profesor/actividad/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:actividad }

ingenieria_profesor_cronograma:
    pattern:  /profesor/cronograma/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:cronograma }

ingenieria_profesor_aprobarcronograma:
    pattern:  /profesor/aprobar-cronograma/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:aprobar }

ingenieria_profesor_rechazarcronograma:
    pattern:  /profesor/rechazar-cronograma/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:rechazar }

ingenieria_profesor_bitacora:
    pattern:  /profesor/bitacora/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:bitacora }

ingenieria_profesor_verificarActividad:
    path:     /profesor/verificaractividad
    defaults: { _controller: IngenieriaProfesorBundle:Default:verificarActividad }

ingenieria_profesor_grupos:
    path:     /profesor/grupos
    defaults: { _controller: IngenieriaProfesorBundle:Default:grupos }

ingenieria_ver_estudiantes_grupo:
    pattern:  /profesor/estudiantes-del-curso/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:estudiantesCurso }

ingenieria_ver_subgrupos:
    pattern:  /profesor/colectivos-del-curso/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:subGrupos }

ingenieria_profesor_registrar_subgrupo:
    pattern:  /profesor/crear-colectivo/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:registrarSubgrupo }

ingenieria_profesor_actualizar_subgrupo:
    pattern:  /profesor/actualizar-colectivo/id={id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:actualizarSubgrupo }

ingenieria_ver_estudiantes_subgrupo:
    pattern:  /profesor/estudiantes-del-colectivo/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:estudiantesSubgrupo }

ingenieria_profesor_estudiantes_singrupos:
    path:     /profesor/estudiantes-sin-colectivos/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:verEstudiantesSinGrupo }

ingenieria_profesor_asignar_subgrupo:
    path:     /profesor/asignar-colectivo/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:asignarSubgrupo }

ingenieria_profesor_ver_encuentros:
    pattern:  /profesor/encuentros/{id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:verEncuentros }

ingenieria_profesor_registrar_encuentro:
    pattern:  /profesor/registrar-encuentro/id={id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:registrarEncuentro }

ingenieria_profesor_actualizar_encuentro:
    pattern:  /profesor/actualizar-encuentro/id={id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:actualizarEncuentro }

ingenieria_profesor_eliminar_subgrupo:
    pattern:  /profesor/eliminar-colectivo/id={id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:eliminarSubgrupo }

ingenieria_profesor_ver_bitacora:
    path:     /profesor/ver-bitacora/id={id}
    defaults: { _controller: IngenieriaProfesorBundle:Default:verBitacora }