parameters:
#    ingenieria_profesor.example.class: Ingenieria\ProfesorBundle\Example

services:
#    ingenieria_profesor.example:
#        class: %ingenieria_profesor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
