<?php

namespace Ingenieria\ProfesorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubgrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubgrupoRepository extends EntityRepository
{
}
