ingenieria_estudiante:
    resource: "@IngenieriaEstudianteBundle/Resources/config/routing.yml"
    prefix:   /

ingenieria_profesor:
    resource: "@IngenieriaProfesorBundle/Resources/config/routing.yml"
    prefix:   /

ingenieria_director:
    resource: "@IngenieriaDirectorBundle/Resources/config/routing.yml"
    prefix:   /

ingenieria_usuario:
    resource: "@IngenieriaUsuarioBundle/Resources/config/routing.yml"
    prefix:   /

logout:
    path:     /logout