security:
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: sha1
            encode_as_base64: false
            iterations:         1
            
        Ingenieria\UsuarioBundle\Entity\Usuario:
            algorithm:        sha1
            encode_as_base64: false
            iterations:         1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                    providers: [in_memory, usuarios]
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    AdmUAO: { password: ef4f5cd341ad8b17d2be9166347033e46400ce0b, roles: [ 'ROLE_ADMIN' ] }
        usuarios:
            entity: { class: Ingenieria\UsuarioBundle\Entity\Usuario, property: username }

                    
    firewalls:
        secured_area:
            pattern:    ^/*
            anonymous: ~
            form_login:
                check_path: usuario_login_check
                login_path: usuario_login
                
            logout:
                path:   /logout
                
            provider:       chain_provider
 
    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/administrador/*, roles: ROLE_ADMIN }
            - { path: ^/director/*, roles: ROLE_DIRECTOR }
            - { path: ^/profesor/*, roles: ROLE_PROFESOR }
            - { path: ^/estudiante/*, roles: ROLE_ESTUDIANTE }
