security:
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: sha1
            encode_as_base64: false
            iterations:         1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    AdmUAO: { password: d0be2dc421be4fcd0172e5afceea3970e2f3d940, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:    ^/*
            anonymous: ~
            form_login:
                check_path: usuario_login_check
                login_path: usuario_login
            logout:
                path:   /logout
 
    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }