ingenieria_director_homepage:
    path:     /director
    defaults: { _controller: IngenieriaDirectorBundle:Default:index }

ingenieria_director_profesores:
    path:     /director
    defaults: { _controller: IngenieriaDirectorBundle:Default:profesores }
    
ingenieria_director_profesores:
    path:     /director/profesores
    defaults: { _controller: IngenieriaDirectorBundle:Default:profesores }
    
ingenieria_director_registrarprofesor:
    path:     /director/registrar-profesor
    defaults: { _controller: IngenieriaDirectorBundle:Default:registrarProfesor }

ingenieria_director_profesor:
    pattern:  /director/profesor/{id}
    defaults: { _controller: IngenieriaDirectorBundle:Default:profesor }

ingenieria_director_actividadesprofesor:
    pattern:  /director/actividades-del-profesor/{id}
    defaults: { _controller: IngenieriaDirectorBundle:Default:actividadesProfesor }

ingenieria_director_actividad:
    pattern:  /director/actividad/{id}
    defaults: { _controller: IngenieriaDirectorBundle:Default:actividad }

ingenieria_director_matricula:
    pattern:  /director/matricula-actividad/{id}
    defaults: { _controller: IngenieriaDirectorBundle:Default:matricula }
