parameters:
#    ingenieria_director.example.class: Ingenieria\DirectorBundle\Example

services:
#    ingenieria_director.example:
#        class: %ingenieria_director.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
