Ingenieria\ProfesorBundle\Entity\Actividad:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '250'
        descripcion:
            type: text
        url:
            type: string
            length: '250'
        imagen:
            type: string
            length: '50'
            nullable: true
        numeroCupos:
            type: integer
            column: numero_cupos
    manyToOne:
        profesor:
            targetEntity: Ingenieria\ProfesorBundle\Entity\Profesor
            inversedBy: actividades
            joinColumn:
                name: profesor
                referencedColumnName: id
        categoria:
            targetEntity: Ingenieria\UsuarioBundle\Entity\Categoria
            inversedBy: actividades
            joinColumn:
                name: categoria
                referencedColumnName: id
    oneToMany:
        estudiantes:
            targetEntity: Ingenieria\EstudianteBundle\Entity\Estudiante
            mappedBy: actividad

    lifecycleCallbacks: {  }
