Ingenieria\ProfesorBundle\Entity\Actividad:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '250'
        mentor:
            type: string
            length: '50'
        email:
            type: string
            length: '50'
        proposito:
            type: string
            length: '250'
        dirigida:
            type: string
            length: '250'
        url:
            type: string
            length: '250'
            nullable: true
        imagen:
            type: string
            length: '50'
            nullable: true
        trabajo:
            type: boolean
            nullable: true
        aprendizaje:
            type: boolean
            nullable: true
        pensamiento:
            type: boolean
            nullable: true
        autonomia:
            type: boolean
            nullable: true
        integralidad:
            type: boolean
            nullable: true
        excelencia:
            type: boolean
            nullable: true
        creatividad:
            type: boolean
            nullable: true
        eticidad:
            type: boolean
            nullable: true
        responsabilidad:
            type: boolean
            nullable: true
        pertenencia:
            type: boolean
            nullable: true
        honestidad:
            type: boolean
            nullable: true
        numeroCupos:
            type: integer
            column: numero_cupos
        horario:
            type: string
            length: '100'
        descripcion:
            type: text
            length: 1000
            nullable: true
        recomendacion:
            type: text
            length: 1000
            nullable: true
    manyToOne:
        categoria:
            targetEntity: Ingenieria\UsuarioBundle\Entity\Categoria
            inversedBy: actividades
            joinColumn:
                name: categoria
                referencedColumnName: id
    oneToMany:
        estudiantes:
            targetEntity: Ingenieria\EstudianteBundle\Entity\Estudiante
            mappedBy: actividad

        subgrupos:
            targetEntity: Ingenieria\ProfesorBundle\Entity\Subgrupo
            mappedBy: actividad

    lifecycleCallbacks: {  }
