Ingenieria\ProfesorBundle\Entity\Profesor:
    type: entity
    table: null
    repositoryClass: Ingenieria\ProfesorBundle\Entity\ProfesorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombres:
            type: string
            length: '50'
        apellidos:
            type: string
            length: '50'
        ci:
            type: string
            length: '12'
            unique: true
        email:
            type: string
            length: '50'
        emailInstitucional:
            type: string
            length: '50'
            column: email_institucional
    oneToMany:
        actividades:
            targetEntity: Ingenieria\ProfesorBundle\Entity\Actividad
            mappedBy: profesor

    lifecycleCallbacks: {  }
