Ingenieria\ProfesorBundle\Entity\Subgrupo:
    type: entity
    table: null
    repositoryClass: Ingenieria\ProfesorBundle\Entity\SubgrupoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '20'

    manyToOne:
        grupo:
            targetEntity: Ingenieria\DirectorBundle\Entity\Grupo
            inversedBy: subgrupos
            joinColumn:
                name: grupo
                referencedColumnName: id

    oneToMany:
        estudiantes:
            targetEntity: Ingenieria\EstudianteBundle\Entity\Estudiante
            mappedBy: subgrupo

    oneToOne:
        lider:
            targetEntity: Ingenieria\EstudianteBundle\Entity\Estudiante
            joinColumn:
                name: lider
                referencedColumnName: id
        actividad:
            targetEntity: Ingenieria\ProfesorBundle\Entity\Actividad
            joinColumn:
                name: actividad
                referencedColumnName: id

lifecycleCallbacks: {  }
