ingenieria_estudiante_homepage:
    path:     /estudiante
    defaults: { _controller: IngenieriaEstudianteBundle:Default:index }

ingenieria_estudiante_cronograma:
    path:     /estudiante/cronograma
    defaults: { _controller: IngenieriaEstudianteBundle:Default:cronograma }

ingenieria_estudiante_actividades:
    path:     /estudiante/activida	des-ofertadas
    defaults: { _controller: IngenieriaEstudianteBundle:Default:actividades }

ingenieria_estudiante_actividad:
    path:     /estudiante/informacion-actividad={id}
    defaults: { _controller: IngenieriaEstudianteBundle:Default:actividad }

ingenieria_estudiante_inscripcion:
    path:     /estudiante/inscripcion={id}
    defaults: { _controller: IngenieriaEstudianteBundle:Default:inscripcion }

ingenieria_estudiante_confirmar:
    path:     /estudiante/confirmar={id}
    defaults: { _controller: IngenieriaEstudianteBundle:Default:confirmar }

ingenieria_estudiante_agregaractividad:
    path:     /estudiante/agregaractividad
    defaults: { _controller: IngenieriaEstudianteBundle:Default:agregaractividad }

ingenieria_estudiante_actividadmatriculada:
    path:     /estudiante/actividad-informacion
    defaults: { _controller: IngenieriaEstudianteBundle:Default:actividadMatriculada }


