ingenieria_estudiante_homepage:
    path:     /estudiante
    defaults: { _controller: IngenieriaEstudianteBundle:Default:index }

ingenieria_estudiante_cronograma:
    path:     /estudiante/cronograma
    defaults: { _controller: IngenieriaEstudianteBundle:Default:cronograma }

ingenieria_estudiante_actividades:
    path:     /estudiante/actividades-ofertadas
    defaults: { _controller: IngenieriaEstudianteBundle:Default:actividades }

ingenieria_estudiante_actividad:
    path:     /estudiante/informacion-actividad={id}
    defaults: { _controller: IngenieriaEstudianteBundle:Default:actividad }

ingenieria_estudiante_inscripcion:
    path:     /estudiante/inscripcion={id}
    defaults: { _controller: IngenieriaEstudianteBundle:Default:inscripcion }

ingenieria_estudiante_confirmar:
    path:     /estudiante/confirmar={id}
    defaults: { _controller: IngenieriaEstudianteBundle:Default:confirmar }

ingenieria_estudiante_agregaractividad:
    path:     /estudiante/agregaractividad
    defaults: { _controller: IngenieriaEstudianteBundle:Default:agregaractividad }

ingenieria_estudiante_actividadmatriculada:
    path:     /estudiante/actividad-informacion
    defaults: { _controller: IngenieriaEstudianteBundle:Default:actividadMatriculada }

ingenieria_estudiante_eliminaractividad:
    path:     /estudiante/eliminaractividad
    defaults: { _controller: IngenieriaEstudianteBundle:Default:eliminaractividad }

ingenieria_estudiante_tutor:
    path:     /estudiante/tutor
    defaults: { _controller: IngenieriaEstudianteBundle:Default:tutor }

ingenieria_estudiante_bitacora:
    path:     /estudiante/bitacora
    defaults: { _controller: IngenieriaEstudianteBundle:Default:bitacora }

ingenieria_estudiante_registrar_actvidad_semanal:
    path:     /estudiante/actividad-semanal
    defaults: { _controller: IngenieriaEstudianteBundle:Default:registrarActividadSemanal }

ingenieria_estudiante_actualizar_actividad_semanal:
    path:     /estudiante/actualizar-actividad-semanal/id={id}
    defaults: { _controller: IngenieriaEstudianteBundle:Default:actualizarActividadSemanal }

ingenieria_estudiante_encuentros:
    path:     /estudiante/encuentro-presencial
    defaults: { _controller: IngenieriaEstudianteBundle:Default:encuentros }