parameters:
#    ingenieria_estudiante.example.class: Ingenieria\EstudianteBundle\Example

services:
#    ingenieria_estudiante.example:
#        class: %ingenieria_estudiante.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
