<?php

namespace Ingenieria\EstudianteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BitacoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BitacoraRepository extends EntityRepository
{
}
