Ingenieria\UsuarioBundle\Entity\Categoria:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
    
    oneToMany:
        actividades:
            targetEntity: Ingenieria\ProfesorBundle\Entity\Actividad
            mappedBy: categoria