Ingenieria\DirectorBundle\Entity\Grupo:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '50'

    oneToMany:
        estudiantes:
            targetEntity: Ingenieria\EstudianteBundle\Entity\Estudiante
            mappedBy: grupo
            cascade: ["persist"]

        subgrupos:
            targetEntity: Ingenieria\ProfesorBundle\Entity\Subgrupo
            mappedBy: grupo
            cascade: ["persist"]

    manyToOne:
        tutor:
            targetEntity: Ingenieria\ProfesorBundle\Entity\Profesor
            inversedBy: grupos
            joinColumn:
                name: tutor
                referencedColumnName: id		

    lifecycleCallbacks: {  }
