usuario_login:
    pattern:   /login
    defaults:  { _controller: IngenieriaUsuarioBundle:Default:login }

usuario_logout:
    pattern:   /logout

usuario_login_check:
    pattern:   /login_check

usuario_inicio:
    pattern:  /
    defaults: { _controller: IngenieriaUsuarioBundle:Default:index }
    
usuario_adm_homepage:
    pattern:  /administrador
    defaults: { _controller: IngenieriaUsuarioBundle:Default:homeAdm }

usuario_registrar_director:
    pattern:  /administrador/registrar-director
    defaults: { _controller: IngenieriaUsuarioBundle:Default:registrarDirector }

usuario_actualizar_director:
    pattern:  /administrador/actualizar-director/id={id}
    defaults: { _controller: IngenieriaUsuarioBundle:Default:director }

usuario_eliminar_director:
    pattern:  /administrador/eliminar-director/id={id}
    defaults: { _controller: IngenieriaUsuarioBundle:Default:eliminarDirector }

usuario_actualizar_estudiante:
    pattern:  /administrador/actualizar-estudiante/id={id}
    defaults: { _controller: IngenieriaUsuarioBundle:Default:actualizarEstudiante }

usuario_cronograma:
    pattern:  /administrador/cronograma-estudiante/id={id}
    defaults: { _controller: IngenieriaUsuarioBundle:Default:cronograma }
    
usuario_estudiantes:
    pattern:  /administrador/cronograma-estudiante
    defaults: { _controller: IngenieriaUsuarioBundle:Default:estudiantes }
    
usuario_registrar_estudiante:
    pattern:  /administrador/registrar-estudiante
    defaults: { _controller: IngenieriaUsuarioBundle:Default:registrarEstudiante }
    
usuario_subirestudiantes:
    pattern:  /administrador/subir-estudiantes
    defaults: { _controller: IngenieriaUsuarioBundle:Default:subirEstudiantes }

usuario_profesores:
    path:     /administrador/profesores
    defaults: { _controller: IngenieriaUsuarioBundle:Default:profesores }
