parameters:
#    ingenieria_usuario.example.class: Ingenieria\UsuarioBundle\Example

services:
#    ingenieria_usuario.example:
#        class: %ingenieria_usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
