parameters:
#    ingenieria_usuario.example.class: Ingenieria\UsuarioBundle\Example

services:
#    ingenieria_usuario.example:
#        class: %ingenieria_usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    my.handler.session_idle:
        class: Ingenieria\UsuarioBundle\Listener\SessionIdleHandler
        arguments: ["@session", "@security.context", "@router", %session_max_idle_time%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
