# src/Ingenieria/UsuarioBundle/Resources/config/validation.yml
Ingenieria\UsuarioBundle\Entity\Document:
    properties:
        file:
            - File:
                maxSize: 6000000
                mimeTypes: [text/plain]
                mimeTypesMessage: Por favor suba un TXT válido
                uploadErrorMessage: El archivo no puede ser cargado!