Ingenieria\EstudianteBundle\Entity\Estudiante:
    type: entity
    table: null
    repositoryClass: Ingenieria\EstudianteBundle\Entity\EstudianteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        codigo:
            type: string
            length: '20'
        ci:
            type: string
            length: '15'
        nombres:
            type: string
            length: '50'
        apellidos:
            type: string
            length: '50'
        email:
            type: string
            length: '50'
            nullable: true
        emailInstitucional:
            type: string
            length: '50'
        aprobadoCronograma:
            type: boolean
            nullable: true
            column: aprobado_cronograma
        rechazadoCronograma:
            type: boolean
            nullable: true
            column: rechazado_cronograma

    oneToMany:
        actividades:
            targetEntity: Ingenieria\EstudianteBundle\Entity\Cronograma
            mappedBy: estudiante
         
        bitacora:
            targetEntity: Ingenieria\EstudianteBundle\Entity\Bitacora
            mappedBy: estudiante

    manyToOne:
        grupo:
            targetEntity: Ingenieria\DirectorBundle\Entity\Grupo
            inversedBy: estudiantes
            joinColumn:
                name: grupo
                referencedColumnName: id
        actividad:
            targetEntity: Ingenieria\ProfesorBundle\Entity\Actividad
            inversedBy: estudiantes
            joinColumn:
                name: actividad
                referencedColumnName: id
    lifecycleCallbacks: {  }
